### ISSUE TITLE
nonebot报错

### ISSUE THREAD

**Issue by TuanKay10** [yaomeng0722/genshin_task-resin-expedition_alert#33]
```
11-29 21:35:31 [ERROR] nonebot | Failed to import "resin_alert"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Program Files\Python38\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\Program Files\Python38\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "D:\Program Files\Python38\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "D:\Program Files\Python38\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "D:\Program Files\Python38\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "D:\Program Files\Python38\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "D:\Program Files\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "d:\Users\Administrator\Documents\mywork\BOT\mybot\bot.py", line 28, in <module>
    nonebot.load_plugins("plugins")
  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\nonebot\plugin\__init__.py", line 1005, in load_plugins
    result = context.run(_load_plugin, manager, plugin_name)
> File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\nonebot\plugin\__init__.py", line 953, in _load_plugin
    module = manager.load_plugin(plugin_name)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\nonebot\plugin\manager.py", line 161, in load_plugin
    return importlib.import_module(f"{self.namespace}.{name}")
  File "D:\Program Files\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\nonebot\plugin\manager.py", line 267, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "plugins\resin_alert\__init__.py", line 6, in <module>
    from .alert import qq_query
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\nonebot\plugin\manager.py", line 267, in exec_module
    super().exec_module(module)
  File "plugins\resin_alert\alert\__init__.py", line 9, in <module>
    from .getinfo.receivedata import receive_data
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\nonebot\plugin\manager.py", line 267, in exec_module
    super().exec_module(module)
  File "plugins\resin_alert\alert\getinfo\receivedata.py", line 4, in <module>
    def receive_data(base_data) -> list[str]:
TypeError: 'type' object is not subscriptable```

**Comment by yaomeng0722** [comment]
咦，可能是receive_data函数出问题了，我有空看看~

**Comment by yaomeng0722** [comment]
> > 咦，可能是receive_data函数出问题了，我有空看看~
> 
> 大佬好，我是一个python萌新，我想问问headers里那个DS是怎么解决的，我想试着自己写个

https://github.com/Azure99/GenshinPlayerQuery/issues/20
具体的可以看这里，涉及到抓包拆包反编译之类的了

**Comment by TuanKay10** [comment]
> [Azure99/GenshinPlayerQuery#20](https://github.com/Azure99/GenshinPlayerQuery/issues/20) 具体的可以看这里，涉及到抓包拆包反编译之类的了

感谢大佬！我参考这个解决了

**Comment by yaomeng0722** [comment]
先试一下不用nonebot能不能正常使用，如果能用的话在alert/\_\_init__.py的64行打个断点，看看base_data是个啥东西，和之前的一不一样，或者点一下单步调试进去试试。看了看区别只在31行和64行指定的格式不一样，但这个应该不影响的

**Comment by TuanKay10** [comment]
> 先试一下不用nonebot能不能正常使用，如果能用的话在alert/__init__.py的64行打个断点，看看base_data是个啥东西，和之前的一不一样，或者点一下单步调试进去试试。看了看区别只在31行和64行指定的格式不一样，但这个应该不影响的

我参考你的重写了一个可以在nonebot运行的，win10可以正常用，换到linux上树脂提醒就有问题了，好像是我用了time. sleep()的问题...不过主动查询是正常的

**Comment by yaomeng0722** [comment]
> > 先试一下不用nonebot能不能正常使用，如果能用的话在alert/**init**.py的64行打个断点，看看base_data是个啥东西，和之前的一不一样，或者点一下单步调试进去试试。看了看区别只在31行和64行指定的格式不一样，但这个应该不影响的
> 
> 我参考你的重写了一个可以在nonebot运行的，win10可以正常用，换到linux上树脂提醒就有问题了，好像是我用了time. sleep()的问题...不过主动查询是正常的

版本一样吗，linux我没测试过，，

**Comment by TuanKay10** [comment]
> > > 先试一下不用nonebot能不能正常使用，如果能用的话在alert/**init**.py的64行打个断点，看看base_data是个啥东西，和之前的一不一样，或者点一下单步调试进去试试。看了看区别只在31行和64行指定的格式不一样，但这个应该不影响的
> > 
> > 
> > 我参考你的重写了一个可以在nonebot运行的，win10可以正常用，换到linux上树脂提醒就有问题了，好像是我用了time. sleep()的问题...不过主动查询是正常的
> 
> 版本一样吗，linux我没测试过，，

我window和linux用的都是python3.8，晚上回去我再试试
